spring.application.name=demo
server.port=8081
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI}
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always
spring.profiles.active=dev
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=30MB
gemini.model=gemini-3.1-flash-lite
